# Generated by Django 4.1.5 on 2023-04-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False),
        ),
        migrations.RunSQL("ALTER TABLE management_employee AUTO_INCREMENT = 100000;"),
    ]
