# Generated by Django 4.1.5 on 2023-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20230419_1008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name'), ('phone_number', 'date_of_birth')},
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
