# Generated by Django 4.1.5 on 2023-04-24 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_user_office_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='office_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.officelocation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='office_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.officelocation'),
        ),
    ]
