# Generated by Django 4.1.5 on 2023-04-26 13:43

from django.db import migrations, models
import django.db.models.deletion
import management.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_employee_office_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationmanagement',
            options={'ordering': ['office_location', '-updated_at'], 'verbose_name': 'Application Management', 'verbose_name_plural': 'Application Management'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['location']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['office_location', '-updated_at'], 'verbose_name': 'Company Employee'},
        ),
        migrations.AddField(
            model_name='location',
            name='office_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='management.officelocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(validators=[management.utils.validators.validate_age_limit]),
        ),
    ]
