# Generated by Django 4.1.5 on 2023-02-16 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_delete_employeeopen_recruiting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeByCoordinator',
        ),
        migrations.CreateModel(
            name='MyEmployeeSection',
            fields=[
            ],
            options={
                'verbose_name': 'My employee',
                'ordering': ['-status', '-updated_at'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.employee',),
        ),
    ]
