# Generated by Django 4.1.5 on 2023-02-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_delete_employeebycoordinator_myemployeesection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='first_name',
        ),
    ]
