# Generated by Django 4.1.5 on 2023-02-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='position_to_apply',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Housekeeping', 'Housekeeping'), ('Houseman', 'Houseman'), ('Community Areas', 'Community Areas'), ('Housekeeping Supervisor', 'Housekeeping Supervisor'), ('Housekeeping Inspector', 'Housekeeping Inspector'), ('Cook', 'Cook'), ('Precook', 'Precook'), ('Bartender', 'Bartender'), ('Steward', 'Steward'), ('Front desk', 'Front desk'), ('Guess services', 'Guess services'), ('Maintenance', 'Maintenance'), ('All the positions', 'All the positions'), ('Other', 'Other')], max_length=25),
        ),
    ]
