# Generated by Django 4.1.5 on 2023-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_application_position_to_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='can_travel',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
    ]
