# Generated by Django 4.1.5 on 2023-04-07 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_application_can_background_check_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingStatus',
            fields=[
            ],
            options={
                'verbose_name': 'Accounting Status',
                'verbose_name_plural': 'Accounting Status',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('management.employee',),
        ),
        migrations.AddField(
            model_name='employee',
            name='quickbooks_status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Not Hired', 'Not Hired'), ('New Employee', 'New Employee'), ('Update Status', 'Update Status'), ('Update Personal Information', 'Update Personal Information'), ('Update Address', 'Update Address'), ('Undefined', 'Undefined')], default='Undefined', max_length=30),
        ),
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_state', to='management.state'),
        ),
    ]
