# Generated by Django 4.1.5 on 2023-04-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_accountingstatus_employee_quickbooks_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingstatus',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Accounting Status', 'verbose_name_plural': 'Accounting Status'},
        ),
        migrations.AlterModelOptions(
            name='employeemanagement',
            options={'ordering': ['updated_at'], 'verbose_name': 'Employee Management', 'verbose_name_plural': 'Employee Management'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='quickbooks_status',
            field=models.CharField(choices=[('Ready', 'Ready'), ('Not Hired', 'Not Hired'), ('New Employee', 'New Employee'), ('Update Personal Information', 'Update Personal Information'), ('Update Address', 'Update Address'), ('Update to Inactive', 'Update to Inactive'), ('Update to Active', 'Update to Active')], default='Not Hired', max_length=30),
        ),
    ]
