# Generated by Django 4.1.5 on 2023-04-13 13:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_accountingstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountingstatus',
            options={'ordering': ['updated_at'], 'verbose_name': 'Accounting Status', 'verbose_name_plural': 'Accounting Status'},
        ),
        migrations.AlterModelOptions(
            name='employeemanagement',
            options={'ordering': ['date_created'], 'verbose_name': 'Employee Management', 'verbose_name_plural': 'Employee Management'},
        ),
        migrations.AlterModelOptions(
            name='myemployeesection',
            options={'ordering': ['-status'], 'verbose_name': 'My employee'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
