# Generated by Django 4.1.5 on 2023-04-13 13:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_alter_accountingstatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency_contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
