# Generated by Django 4.1.5 on 2023-01-04 17:01

from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.state'))

            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.city')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.location'))
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('type', models.CharField(choices=[('Payroll', 'Payroll'), ('I9', 'I9'), ('Regular', 'Regular')], default='Regular', max_length=10)),
                ('zip_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Interview', 'Interview')], default='Interview', max_length=10)),
                ('date_created', models.DateTimeField(default=mainApp.models.current_time)),
                ('updated_at', models.DateTimeField(default=mainApp.models.current_time)),
                ('job', models.ForeignKey(default=mainApp.models.get_default_none_job, on_delete=django.db.models.deletion.CASCADE, to='mainApp.job')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.city')),
            ],
        ),
        
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reference', models.CharField(blank=True, max_length=50)),
                ('Start_date', models.DateField()),
                ('End_date', models.DateField()),
                ('Regular_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Regular_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Overtime_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Overtime_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Extra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(max_length=20)),
                ('Payment_date', models.DateField(blank=True, null=True)),
                ('Withdrawn_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.employee')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allergic_to', models.CharField(blank=True, max_length=50)),
                ('diseases_suffered', models.CharField(blank=True, max_length=50)),
                ('received_workers_compensation', models.BooleanField(default=False)),
                ('received_surgery_for_fracture', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.employee')),
            ],
        ),
        
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.job')),
            ],
        ),
        migrations.CreateModel(
            name='FrequentPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.employee')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('relationship', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Passport', 'Passport'), ('Driver license', 'Driver license'), ('ID card', 'ID card'), ('Social security card', 'Social security card'), ('Work permit', 'Work permit')], max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('date_of_expiration', models.DateField()),
                ('file', models.FileField(upload_to='employee_documents/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_available_to_work', models.CharField(choices=[('Mon-Fri', 'Monday to Friday'), ('Mon-Sat', 'Monday to Saturday'), ('Mon-Sun', 'Monday to Sunday')], max_length=8)),
                ('can_travel', models.BooleanField()),
                ('can_work_nights', models.BooleanField()),
                ('can_background_check', models.BooleanField()),
                ('position_to_apply', models.CharField(choices=[('Manager', 'Manager'), ('Housekeeping', 'Housekeeping'), ('Houseman', 'Houseman'), ('Community Areas', 'Community Areas'), ('Supervisor', 'Supervisor'), ('Inspector', 'Inspector'), ('Cook', 'Cook'), ('Precook', 'Precook'), ('Bartender', 'Bartender'), ('Steward', 'Steward'), ('Front desk', 'Front desk'), ('Guess services', 'Guess services'), ('Maintenance', 'Maintenance'), ('All the positions', 'All the positions'), ('Other', 'Other')], max_length=17)),
                ('experience', models.CharField(choices=[('Manager', 'Manager'), ('Housekeeping', 'Housekeeping'), ('Houseman', 'Houseman'), ('Community Areas', 'Community Areas'), ('Supervisor', 'Supervisor'), ('Inspector', 'Inspector'), ('Cook', 'Cook'), ('Precook', 'Precook'), ('Bartender', 'Bartender'), ('Steward', 'Steward'), ('Front desk', 'Front desk'), ('Guess services', 'Guess services'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=15)),
                ('english_level', models.CharField(choices=[('None', 'None'), ('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Fluent', 'Fluent')], max_length=12)),
                ('studies', models.BooleanField()),
                ('military_service', models.BooleanField()),
                ('file', models.FileField(upload_to='applications/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.employee')),
            ],
        ),
    ]
