# Generated by Django 4.1.5 on 2023-01-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.CharField(choices=[('None', 'None'), ('Manager', 'Manager'), ('Housekeeping', 'Housekeeping'), ('Houseman', 'Houseman'), ('Community Areas', 'Community Areas'), ('Supervisor', 'Supervisor'), ('Inspector', 'Inspector'), ('Cook', 'Cook'), ('Precook', 'Precook'), ('Bartender', 'Bartender'), ('Steward', 'Steward'), ('Front desk', 'Front desk'), ('Guess services', 'Guess services'), ('Maintenance', 'Maintenance'), ('Other', 'Other')], max_length=15),
        ),
    ]
