# Generated by Django 4.1.5 on 2023-01-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_application_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeByCoordinator',
            fields=[
            ],
            options={
                'verbose_name': 'Employee',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mainApp.employee',),
        ),
        migrations.CreateModel(
            name='EmployeeInterview',
            fields=[
            ],
            options={
                'verbose_name': 'Interview',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mainApp.employee',),
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Company Employee'},
        ),
        migrations.CreateModel(
            name='Employee_head',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='mainApp.employee')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head', to='mainApp.employee')),
            ],
        ),
    ]
