# Generated by Django 4.1.5 on 2023-01-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_employeebycoordinator_employeeinterview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='specialty_of_studies',
            field=models.CharField(default=0.000501002004008016, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='studies',
            field=models.CharField(choices=[('None', 'None'), ('High school', 'High school'), ('University', 'University')], max_length=12),
        ),
    ]
