# Generated by Django 4.1.5 on 2023-02-14 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='application_status',
            field=models.CharField(choices=[('Regular Application', 'Regular Application'), ('No Application', 'No Application'), ('Undefined', 'Undefined'), ('Southeast', 'Southeast'), ('FrontDesk', 'FrontDesk'), ('Human Resources', 'Human Resources')], default='Undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Application', 'Application'), ('Southeast', 'Southeast'), ('Form', 'Form'), ('Passport', 'Passport'), ('Driver license', 'Driver license'), ('ID card', 'ID card')], max_length=20),
        ),
    ]
