# Generated by Django 4.1.5 on 2023-01-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_application_specialty_of_studies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalform',
            name='received_surgery_for_fracture',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalform',
            name='received_workers_compensation',
            field=models.CharField(max_length=100),
        ),
    ]
