# Generated by Django 4.1.5 on 2023-02-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_employee_application_status_alter_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeApplicationStatusUndefined',
            fields=[
            ],
            options={
                'verbose_name': 'Application management',
                'verbose_name_plural': 'Application management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mainApp.employee',),
        ),
    ]
