# Generated by Django 4.1.5 on 2023-01-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_alter_medicalform_received_surgery_for_fracture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='file',
        ),
        migrations.RemoveField(
            model_name='document',
            name='number',
        ),
        migrations.AlterField(
            model_name='document',
            name='date_of_expiration',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Application', 'Application'), ('Passport', 'Passport'), ('Driver license', 'Driver license'), ('ID card', 'ID card'), ('Social security card', 'Social security card'), ('Work permit', 'Work permit')], max_length=20),
        ),
    ]
