# Generated by Django 4.1.5 on 2023-02-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_employeeapplicationstatusundefined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeApplicationStatusUndefined',
        ),
        migrations.CreateModel(
            name='EmployeeManagement',
            fields=[
            ],
            options={
                'verbose_name': 'Employee Management',
                'verbose_name_plural': 'Employee Management',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mainApp.employee',),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Stand By', 'Stand By'), ('Do Not Hire', 'Do Not Hire'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Undefined', 'Undefined')], default='Undefined', max_length=15),
        ),
    ]
