# Generated by Django 4.1.5 on 2023-01-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_remove_application_file_remove_document_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='days_available_to_work',
            field=models.CharField(choices=[('Monday to Friday', 'Monday to Friday'), ('Monday to Saturday', 'Monday to Saturday'), ('Monday to Sunday', 'Monday to Sunday')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='experience',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='specialty_of_studies',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('Application', 'Application'), ('Form', 'Form'), ('Passport', 'Passport'), ('Driver license', 'Driver license'), ('ID card', 'ID card'), ('Social security card', 'Social security card'), ('Work permit', 'Work permit')], max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalform',
            name='allergic_to',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalform',
            name='diseases_suffered',
            field=models.CharField(max_length=100),
        ),
    ]
