# Generated by Django 4.1.5 on 2023-02-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_employeebycoordinator_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeOpen',
        ),
        migrations.CreateModel(
            name='Recruiting',
            fields=[
            ],
            options={
                'verbose_name': 'Recruiting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mainApp.employee',),
        ),
    ]
