# Generated by Django 4.1.5 on 2023-01-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_alter_application_days_available_to_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='date_of_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
