# Generated by Django 4.1.5 on 2023-01-26 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_document_date_of_expiration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_head',
            options={'verbose_name': 'Coordinator Employee'},
        ),
        migrations.AlterModelOptions(
            name='employeebycoordinator',
            options={'verbose_name': 'Employee By Coordinator Deprecated'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='job',
        ),
        migrations.AlterField(
            model_name='employee_head',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeOfHead', to='mainApp.employee'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='location'),
        ),
        migrations.CreateModel(
            name='Employee_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='mainApp.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='mainApp.job')),
            ],
        ),
    ]
