# Generated by Django 4.1.5 on 2023-01-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_alter_employee_head_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_head',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeeWithHead', to='mainApp.employee'),
        ),
    ]
