# Generated by Django 4.1.5 on 2023-02-01 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_alter_employee_head_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOpen',
            fields=[
            ],
            options={
                'verbose_name': 'Recruiting',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mainApp.employee',),
        ),
        migrations.AlterModelOptions(
            name='emergency_contact',
            options={'verbose_name': 'Emergency Contact'},
        ),
        migrations.AlterModelOptions(
            name='employee_head',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employee_job',
            options={'verbose_name': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='employeebycoordinator',
            options={'verbose_name': 'My employee'},
        ),
        migrations.AlterField(
            model_name='application',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_employee', to='mainApp.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='employee_job',
            unique_together={('employee', 'job')},
        ),
    ]
