# Generated by Django 4.1.5 on 2023-02-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_rename_name_employee_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='mail',
            new_name='email',
        ),
    ]
