# Generated by Django 4.1.5 on 2023-02-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_employeeopen_alter_emergency_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_job',
            options={'verbose_name': 'Employee Job'},
        ),
        migrations.AlterField(
            model_name='employee_job',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_job_employee', to='mainApp.employee'),
        ),
    ]
