# Generated by Django 4.1.5 on 2023-02-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_rename_mail_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Stand By', 'Stand By'), ('Do Not Hire', 'Do Not Hire'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Undefined', 'Undefined')], default='Undefined', max_length=15, verbose_name='Status'),
        ),
    ]
