"""
Django settings for EMS project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

import os
from django.utils.translation import gettext_lazy as _
from django.conf.locale import LANG_INFO
from django.conf import global_settings
gettext_noop = lambda s: s

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j%y5@-3-ufqlp(ksm^51#!*f2q(j1s$fa@5@i-)s0#xbgbtvh^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'management',
    'crispy_forms',
    'wkhtmltopdf',
    # "django_rename_app",
    "phonenumber_field",
    #'address',
    'django.forms'
]
FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'

GOOGLE_MAPS_API_KEY = 'AIzaSyBoMcrb65POH2WYo0AV2ecsgwxz6sGN2iw'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EMS.urls'

#os.path.join(BASE_DIR, "templates"), 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [os.path.join(BASE_DIR, 'templates/')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EMS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE'  : 'django.db.backends.mysql',
        'NAME'    : 'mytestdb',                 # <-- UPDATED line 
        'USER'    : 'root',                     # <-- UPDATED line
        'PASSWORD': 'Alejandro16=',              # <-- UPDATED line
        'HOST'    : 'localhost',                # <-- UPDATED line
        'PORT'    : '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'

LANGUAGES = (
    ('en', _('English')),
    ('es', _('Español')),
    ('ht', _('Haitian Creole')),
)
EXTRA_LANG_INFO = {
    'ht': {
        'bidi': True, # right-to-left
        'code': 'ht',
        'name': 'Haitian Creole',
        'name_local': 'Kreyòl ayisyen', #unicode codepoints here
    },
}

# Add custom languages not provided by Django
import django.conf.locale
LANG_INFO = dict(django.conf.locale.LANG_INFO, **EXTRA_LANG_INFO)
django.conf.locale.LANG_INFO = LANG_INFO

#Esto causa que el panel de administrador se vea invertido horizontalmente, por eso lo comenté
# Languages using BiDi (right-to-left) layout
#LANGUAGES_BIDI = global_settings.LANGUAGES_BIDI + ["ht"]

TIME_ZONE = 'UTC'

USE_I18N = True
USE_L10N = False
USE_TZ = True
DATE_INPUT_FORMATS = [
    "%m/%d/%Y",  # '10/25/2006'
    "%m/%d/%y",  # '10/25/06'
    ]

# URL de cambio de idioma
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_SESSION_KEY = 'django_language'
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-gray-dark navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "flatly",
    #"theme": "solar",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}

JAZZMIN_SETTINGS = {
    "site_brand": "Administration Panel",
    "language_chooser": True,
    "show_ui_builder": True,
    "welcome_sign": "Welcome",
    "login_logo": None,
    # "topmenu_links": [

    #     # Url that gets reversed (Permissions can be added)
    #     {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},

    #     # external url that opens in a new window (Permissions can be added)
    #     {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},

    #     # model admin to link to (Permissions checked against model)
    #     {"model": "auth.User"}, 

    #     # App with dropdown menu to all its models pages (Permissions checked against models)
    #     {"app": "management"},    
    # ],
    # Additional links to include in the user menu on the top right ("app" url type is not allowed)
    # "usermenu_links": [
    #     {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    #     {"model": "auth.user"}
    # ],
    "show_sidebar": True,
    #"navigation_expanded": False,
    
    #fontawesome 5.13 version

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-tie",
        "auth.Group": "fas fa-users-cog",
        "management.employee": "fas fa-users",
        "management.department": "far fa-building",
        "management.job": "fas fa-briefcase",
        "management.location": "fas fa-map-pin",
        "management.MyEmployeeSection": "fas fa-address-book",
        "management.recruiting": "fas fa-phone-volume",
        "management.EmployeeInterview": "far fa-clipboard",
        "management.ApplicationManagement": "fas fa-user-cog",
        "management.AccountingStatus": "fas fa-money-check-alt",
        "management.Frontdesk": "fas fa-user-friends",
        #"management.AccountingStatus": "fas fa-file-invoice"

    },
    "related_modal_active": True,
    # "custom_links": {
    #     "management": [{
    #         "name": "Make Messages", 
    #         #"url": "/admin/management/employee/?status__exact=Interview", 
    #         "url": "admin/home",
    #         "icon": "fas fa-comments",
    #         "permissions": []
    #     }]
    # },
    #"hide_models": ["management.employee"]
}

CRISPY_TEMPLATE_PACK = 'bootstrap4'
CRISPY_FAIL_SILENTLY = not DEBUG

MEDIA_ROOT = os.path.join(BASE_DIR, 'EMS')
MEDIA_URL = '/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
AUTH_USER_MODEL = 'management.User'
LOGIN_URL = 'admin:login'
#Me permite usar el popup de add en el panel de administrador
X_FRAME_OPTIONS = 'SAMEORIGIN'
